### ISSUE TITLE
Add instructions for increasing Windows UDP receive buffer size

### ISSUE THREAD

**Issue by simbaforrest** [lcm-proj/lcm-proj.github.io#1]
Just for completeness, adding instructions for increasing Windows OS's UDP receive/send buffer size in the [UDP Multicast Setup](http://lcm.googlecode.com/svn/www/reference/lcm/multicast.html) might be easier for Windows users.

Corresponding to modifying /etc/sysctl.conf in Linux, in Windows one can modified registry by copying the following content in a LCM_UDP_buffer_limit.reg file, double-clicking it (changing send/receive buffer size to 2MB) and finally restarting the computer:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\AFD\Parameters]
"DefaultReceiveWindow"=dword:00200000
"DefaultSendWindow"=dword:00200000
```

For more explanation one may check:
1. https://technet.microsoft.com/en-us/library/bb726981.aspx#EBAA
2. http://stackoverflow.com/questions/18985816/change-default-socket-buffer-size-under-windows

**Comment by ashuang** [comment]
Thanks, I've modified the docs and added that information.
