### ISSUE TITLE
update build instructions

### ISSUE THREAD

**Issue by bluesquall** [lcm-proj/lcm-proj.github.io#4]
The [build instructions](http://lcm-proj.github.io/build_instructions.html) at lcm-proj.github.io don't include the change to CMake, but it looks like [build-instructions.md](https://github.com/lcm-proj/lcm/blob/master/docs/content/build-instructions.md) has already been updated.

Perhaps all that is needed is to run the scripts to generate the HTML, and then push the result to the github-pages repo?

**Comment by nosracd** [comment]
The instructions have been updated.
